### ISSUE TITLE
Someone successfully implemented this into homebridge...

### ISSUE THREAD

**Issue by ctschach** [simont77/fakegato-history#1]
The subject says it all - is there any accessory where this has been successfully implemented?

**Comment by simont77** [comment]
Hi,
you can try this Weather Underground plugin, which I adapted to use fakegato-history https://github.com/simont77/homebridge-weather-station-extended (this is actually the plugin I used for testing). Note that you would also need this custom module https://github.com/simont77/wundergroundnode and not the standard one on NPM.
It's still a work in progress, right now I'm implementing the rolling over of the memory, and try to improve data download when more iOS are used.
