### ISSUE TITLE
Where is the history file?

### ISSUE THREAD

**Issue by stevemac00** [simont77/fakegato-history#101]
Thank you for the useful code. Fakegato is reporting temperature to Eve and it shows up in the Eve graphing. But I can't see any evidence of the history file.

log snippet (cleaned up removing color code, date)
```
Fakegato-storage AddWriter : undefined
Temperature Loading...
Temperature Fakegato-storage read FS file: /history/aqua_undefined_persist.json
Temperature Fakegato-timer Subscription : undefined
Temperature Registring Events undefined
```
code snippet
`this.loggingService = new FakeGatoHistoryService("weather", this, {storage:'fs',path:'/history'})`

This is in an oznu/homebridge container with root access in the container and I tested for perms in /history. Any ideas for debugging? Is that empty normal for the AddWriter?

P.S. "Registring" is misspelled - should be "Registering"

**Comment by simont77** [comment]
Apparently you did not set the AccessoryName properly, hence the "undefined". I'm not sure if this will also interfere with the creation of the persist file.

**Comment by stevemac00** [comment]
You're right, a space. I should've thought of that.
