### ISSUE TITLE
Question about gaps in history

### ISSUE THREAD

**Issue by seydx** [simont77/fakegato-history#106]
Hi guys,

Currently I use fakegato for different plugins and types. I have a problem with gaps in my history.

I have implemented the .addEntry in the ``.on('change')`` event. So every time there is a change, the plugin will also add a new entry. The problem is that this does not happen periodically. Does this cause the problem with the gaps in the history?

 I thought FakeGato would add additional entries to avoid this?

**Comment by simont77** [comment]
Which type are you using? Fakegato adds entries only if you enable the timer and only for certain types.

**Comment by seydx** [comment]
@simont77 

i thought the timer is always enabled until i disable it?

> By default, if you don't addEntry during the 10 minutes timer, to avoid gaps (and fill data for lazy sensors), the timer repeat the last data.

im using following types:

- energy
- room
- door
- motion
- thermo

**Comment by simont77** [comment]
Yes, the timer is active by default. Which version of fakegato are you using? Maybe the last update broke up the timer.

**Comment by seydx** [comment]
@simont77 

v0.6.1 , but it was already on the previous version too

**Comment by simont77** [comment]
you mean 0.6.0? Version 0.5.x has not been touched for a long time and there was no issue reported for the timer.

**Comment by seydx** [comment]
yes v0.6.0

**Comment by simont77** [comment]
Could you try with 0.5.6?
