### ISSUE TITLE
Limit reporting to a single service

### ISSUE THREAD

**Issue by matej** [simont77/fakegato-history#110]
I have an accessory set up which has multiple service. It's an all-in-one home climate device that includes thermostats / fan / temperature sensors / etc. I've been experimenting with fakegato support to add some logging for the main thermostat service. 

Reporting works, but the issue is that the data is shared and displayed under all services for the accessory, which means it's nonsense for all but the service it's meant for. Is there any way to specify which service the data relates to? Is that even supported by the protocol? 

Some images for illustration (it's all the same data, just the current value is added to the end which makes the charts look a bit different):

![IMG_0330](https://user-images.githubusercontent.com/91322/103227778-7cbd3f80-492f-11eb-8a37-334d2d3d47ae.PNG)

![IMG_0331](https://user-images.githubusercontent.com/91322/103227783-80e95d00-492f-11eb-9fc0-06c58d99add3.PNG)

![IMG_0332](https://user-images.githubusercontent.com/91322/103227784-82b32080-492f-11eb-950d-a8afe7046b5f.PNG)

**Comment by simont77** [comment]
As far as I know, Eve.app only supports one history service per accessory, so what you ask is not allowed.

**Comment by matej** [comment]
Thank you for the feedback. After spending some more time on this, that's unfortunately my conclusion as well. This seems to be a dead end.
