### ISSUE TITLE
Light Effect Characteristic?

### ISSUE THREAD

**Issue by dsully** [simont77/fakegato-history#112]
I'm trying to dive deeper into what I believe is a Light Effect Characteristic, defined as UUID:

F8600004-079E-48FF-8F27-9C2605A29F52

that is exposed in the Eve app. The Vocolinc Lightbud appears to implement this as well.

**Comment by HomeKidd** [comment]
Hi!

Its not implemented by Eve, i've created this characteristic.

```
    permissions : homekit_permissions_paired_read, homekit_permissions_paired_write, homekit_permissions_notify
    min_value : 0
    max_value : 53
    min_step : 1
    format : HOMEKIT_UINT8
```

You can define any custom characteristics (and services) you want with a custom UUID but these characteristics are not showing up in the Home app, only in 3rd party apps 🤓

_Originally posted by @HomeKidd in https://github.com/HomeKidd/Homekit-WS2812B-controller/issues/40#issuecomment-781137375_
