### ISSUE TITLE
Eve Thermo (2020) Thread firmware new services/characteristics

### ISSUE THREAD

**Issue by ebaauw** [simont77/fakegato-history#113]
With the Eve Thermo (2020) firmware with Thread support finally out, I got myself a duo pack.  I have no luck with my Zigbee TRVs, so I'm trying these instead.

The Eve Thermo shows two new (Apple-defined, but undocumented) services, presumable to report the Thread protocol info.  The Eve Energy (4th-gen EU) carries the same services.  All the characteristics are read-only.  Not sure if these are at all useful, but I figured I might as well share them.

Service | Characteristic | Type | Meaning
--- | --- | --- | ---
701 | 702 | int | shows `2` on the Thermos, and `8` on the Energy, presumably _Thread Status_ or _Capabilities_
701 | 703 | int | shows `8` on the Thermos, and `16` on the Energy presumably _Thread Status_ or _Capabilities_
701 | 706 | string | OpenThread stack id string
701 | 22B | boolean | shows `On`, presumably _Transport_
239 | 23A | int | Sleep Interval (in ms); `5000` for the Thermos, `0` for the Energy
239 | 23C | tlv (?) | shows `<>`
239 | 24A | integer | shows `1` on one Thermo and `3` on the other, and `23` for the Energy.

There's a custom characteristic, 34AB8811-AC7F-4340-BAC3-FD6A85F9943B, on the _Accessory Information_ service.  I'm puzzled who defined it, as it doesn't follow the Eve UUID scheme.  Its value is `"5.2";30b0d575` on the Thermo, and `"5.0";e0258992` on the Energy.  I looks to be a firmware (file) version, but I cannot relate these to the versions reported under _Firmware_.  

I cannot find anything related to _Installation_ (incl. _Orientation_), _Temperature Offset_, _Valve Protection_, _Child Lock_.  I think it might be set in _Program Command_ (127) and reported in _Program Data_ (12F), together with the schedule.  I use (Apple-defined) _Lock Physical Controls_ when exposing the Zigbee thermostats, and Eve shows that as _Child Lock_, identifying the device as an Eve Thermo (2015).

**Comment by n0rt0nthec4t** [comment]
Curious what is the reported firmware version for the 2020 Thermo?

**Comment by ebaauw** [comment]
2.1.1 (2834)

**Comment by n0rt0nthec4t** [comment]
Thanks.. something to play around later to see how to get EveHome to show a thermostat service as a 2020 one (rather than 2015). One thing I've not been able to get working is when Eve app thinks its a 2015 thermo, under settings don't get the temperature units to show. more to play with when have time
