### ISSUE TITLE
Feature Request: Eve Weather now support history for Light Level

### ISSUE THREAD

**Issue by dacarson** [simont77/fakegato-history#126]
When I view an Eve Weather Station, it has light level history. It would be great if the Weather history also supported light level.

**Comment by dacarson** [comment]
This might be the same request as:
https://github.com/simont77/fakegato-history/issues/109

**Comment by wimleers** [comment]
Yep, this looks like a duplicate.

Provided extra info at https://github.com/simont77/fakegato-history/issues/109#issuecomment-1605316707.

**Comment by dacarson** [comment]
Closing as a duplicate
