### ISSUE TITLE
Feature request: make timer subscription optional

### ISSUE THREAD

**Issue by ebaauw** [simont77/fakegato-history#30]
I'd like to be able to specify per accessory whether the logging service should subscribe to the fakegato timer.  A lot of ZigBee sensors report their state periodically, which I can use easily to create periodic entries.

Also, for plugins that poll devices and cache their state it's quite easy to create periodic entries every n-th polling cycle.

**Comment by NebzHB** [comment]
ok, will do that.  Please note Eve is waiting for data every 10min and regularly nevertheless (all Eve devices give data every 10min).

**Comment by NebzHB** [comment]
it's done in the branch fakegato-storage (future master).
