### ISSUE TITLE
Gaps in history

### ISSUE THREAD

**Issue by honkmaster** [simont77/fakegato-history#32]
In my setup  I have integrated two components with `fakegato-history`support:

1. `homebridge-weather`
2. `homebridge-dht`

Sometimes I have gaps in my history inside the Eve app (see attached screenshot, sorry for the German). My server has been running constantly without errors. The log files are inconspicuous and the components have logged their data well. This is e.g. a log from the time where no history is available:

```
[2018-2-1 15:14:42] [Wetter] Fetched humidity 86 of type current for Wetter
[2018-2-1 15:14:42] [Wetter] Fetched temperature 4 of type current for Wetter
[2018-2-1 15:15:12] [DHT22] DHT Status: 0, Temperature: 17.6, Humidity: 53
```
Do you have any idea what causes this issue and how can I help?

![img_7997](https://user-images.githubusercontent.com/1380397/35698522-94d8e3d0-078d-11e8-9f41-279e828c609d.PNG)

**Comment by simont77** [comment]
which version of fakegato are you using? we are making many addition and fixes in the last few weeks. Are you using the standard history size on 4032 samples? Are you sure you are calling addEntry every time?

**Comment by NorthernMan54** [comment]
One thing to keep in mind is that the data is cached in memory and if homebridge restarts, data is lost. And if the client has not been updated lately, data gaps will occur.

**Comment by honkmaster** [comment]
I am **only a user** of those plugins **not the developer**. If I am looking right, they both use 4032 samples and at least homebridge-weather is using the latest version and calling addEntry every time.

**Comment by simont77** [comment]
I see in the graph that points are not periodic (especially in the last part). Are you sure that your plugin is calling addEntry about every 10 min? @NebzHB had a similar problem with a  “lazy sensor” that does not produce any event if the temperature variation is small. Now we added to fakegato an internal timer to produce in any case an entry every 10 min repeating the last one

**Comment by honkmaster** [comment]
Regarding the un-periodic entries for`homebridge-weather`. Here you can define a polling interval, which is 10 minutes for my configuration, thus I would expect an update every 10 minutes. I have no idea... maybe @werthdavid can help. He is the developer of the plugin.

**Comment by NorthernMan54** [comment]
I know DHT is updating regularly, as that one is mine.

Are you sure about the server not restarting?

**Comment by simont77** [comment]
do you have the same holes also in DHT?

**Comment by werthdavid** [comment]
I'm pretty sure that homebridge-weather updates on a regular basis. Not 100% though since I have never verified it with the log-file.

**Comment by simont77** [comment]
and do you have any problem?

Inviato da iPad

**Comment by werthdavid** [comment]
I cant verify until Monday unfortunately..

**Comment by honkmaster** [comment]
I have the same holes in DHT. Could this issue also be related to #33, https://github.com/ebaauw/homebridge-hue/issues/277 and the recent update to the Eve app (3.1/943)?

**Comment by simont77** [comment]
dont' think so, I have also update to Eve 3.1 with no issue, and DHT was deeply tested by @NorthernMan54. If your server is still up, try to delete all history, force close Eve and reload

**Comment by NorthernMan54** [comment]
I think we can close this
