### ISSUE TITLE
Name of _persist.json file

### ISSUE THREAD

**Issue by ebaauw** [simont77/fakegato-history#46]
I'm having some concerns on the fakegato-storage functionality, particularly the filenames used:
- When using `{storage: 'fs'}` as option to `FakeGatoHistory`, it doesn't seem to make sense to use the hostname in the filename.  Multiple instances of homebridge need to be run from a different user directory anyway, ensuring each instance logs to a different directory;
- The accessory displayName is not guaranteed to be unique and might actually change over time.  Also it might contain spaces.  I'd rather see the accessory serial number in the filename.  Still I would like to base the name of the history service on the accessory display name. 

Arguably, not every-one might share my concerns.  Both issues could be addressed by adding an additional `filename` option to the `FakeGatoHistory`, so each plugin can control their own behaviour.

**Comment by NorthernMan54** [comment]
Erik,

Do you know if we have access to the serial number as part of the object?   I think in the platform V2 API we should be able to access the information service, but in the accessory or V1 I don’t think it is accessible.

For the hostname, that was for me where I have a test environment, plus production and I overwrote the data numerous times.

I’m okay with your thoughts, and enhancements.

**Comment by ebaauw** [comment]
Thanks, Sean.

> Do you know if we have access to the serial number as part of the object?

That would indeed be up to the plugin.  We could use a convention that it should be in `accessory.serialNumber`, just like using `accessory.displayName`, but I think it's safer to just pass it as parameter.

I'm actually now storing the persist files in `~/.homebridge/accessories` (or `accessories` in the user path).  Seems to make sense to me, as homebridge stores the persisted accessories there as well, for V2 platform plugins.

**Comment by NorthernMan54** [comment]
Sounds good.

PS For majority of my devices the display name is the serial number, ( I have a dozen nodemcu based temperature sensors and I just used the hostname “node-aabbccddeeff” as the display name ).  So when I look at my googledrive, they are serial numbers.
