### ISSUE TITLE
Can only see "undefined" when passing 'this' as an Accessory.

### ISSUE THREAD

**Issue by mylesagray** [simont77/fakegato-history#47]
Hi,

I added fakegato-history to my accessory i'm working on with the below:

    this.loggingService = new FakeGatoHistoryService("room", this, {
      storage:'fs'
      });
    this.services.push(this.loggingService);

However when the plugin loads in debug mode all I see is:

    [2018-3-2 05:29:33] [BlueAir 680i] ** Fakegato-storage AddWriter : undefined
    [2018-3-2 05:29:33] [BlueAir 680i] Loading...
    [2018-3-2 05:29:33] [BlueAir 680i] ** Fakegato-storage read FS file: 
    /Users/myles.gray/.homebridge/Myless-MacBook-Pro.local_undefined_persist.json
    [2018-3-2 05:29:33] [BlueAir 680i] ** Fakegato-timer Subscription : undefined
    [2018-3-2 05:29:33] [BlueAir 680i] Registring Events undefined
    [2018-3-2 05:29:33] [BlueAir 680i] Accessory undefined

I have followed the instructions as best I can, I have made sure `this.log = log;` is also in the accessory constructor.

Any ideas?

**Comment by ebaauw** [comment]
Fakegato expects a `this.displayName`.

**Comment by simont77** [comment]
you probably don’t have displayName properties in your accessory

**Comment by mylesagray** [comment]
Thanks guys, that appears to be working now and displaying history for Temp and Humidity, however Air Quality is showing no data in measurements or the graph - debug output showing as expected however - passing particulate data in ppm:

    [2018-3-2 13:18:21] [BlueAir 680i] **Fakegato-timer: addData  BlueAir 680i { time: 1519996701,
      temp: 20.464,
      humidity: 29.698,
      ppm: 6.686035 }  immediate:  false

**Comment by simont77** [comment]
Did you add the custom characteristic E863F10B for ppm?

**Comment by mylesagray** [comment]
I didn't, but I don't see that in the docs anywhere?

**Comment by simont77** [comment]
"Your plugin should expose the corresponding custom Elgato services and characteristics in order for the history to be seen in Eve.app." :-)
Have a look at the characteristics list in the wiki.

**Comment by mylesagray** [comment]
Excellent, sorry about that @simont77 - I've implemented it now and working as expected, are you opposed to me doing some documentation revisions to try and make it easier to follow for outsiders and non-programmers (like me) and issuing a PR?

**Comment by simont77** [comment]
No problem at all, any help is appreciated
