### ISSUE TITLE
Latest Entry/value

### ISSUE THREAD

**Issue by seydx** [simont77/fakegato-history#50]
Hello everyone, 

First of all, thank you so much for this awesome work. Im using it with my Thermostat Plugin. Everything works fine. 

So i wanted to create something new in regard of the Motion Sensors. And therefore i wanted to know if its possible to get the latest Entry (time, Status value) from Fakegato history

**Comment by simont77** [comment]
It’s not a supported functionality, but you should be able to access the latest entry with something like fakegato.history[fakegato.lastEntry]. Why do you need it? You should alredy know which is the last entry you added.

**Comment by seydx** [comment]
Hey, thanks, i already solved the Problem :)

**Comment by tobekas** [comment]
Hi, `fakegato.history[fakegato.lastEntry]` does not do the job after wrap-around.
The solution is `fakegato.history[fakegato.lastEntry % fakegato.memorySize]`

**Comment by souimanga** [comment]
Hi, 

I'm currently using a homebrdige service on rp3 with homebridge-Xiaomi-plant care plugin.
Works fine, it's working with fakegato-history too. 
https://github.com/honkmaster/homebridge-mi-flower-care

But, I would like to display the lastest time on records

Do you have an idea ?

Thanks
