### ISSUE TITLE
History not showing in Elgato EVE

### ISSUE THREAD

**Issue by EIBHomeControl** [simont77/fakegato-history#51]
Hi,

i've created some new accessories with fakegato. Everthing seems to work correctly. 
How can i force the accessory to show the history? I've tried to remove the accessory from the homebridge and readd it again. Nothing happens. Is there a other solution than to completly remove the homebridge?

regards

**Comment by simont77** [comment]
History will show up only if you added the Elgato extra custon characteristics for the type of accessory you are using. If you already did that, try to force quit Eve and reopen it.

**Comment by EIBHomeControl** [comment]
@simont77 Elgato extra characteristics already added. Force quit didn't work. just installed Hesperus. Seems that the custom characteristics not added correctly to my custom temperature sensor.

**Comment by simont77** [comment]
Do you mean the extra characteristics? Post your code here

**Comment by EIBHomeControl** [comment]
jep. 
see my last 3 commit 
https://github.com/EIBHomeControl/homebridge-http-webhooks

**Comment by simont77** [comment]
There is typo at line 426. Could be that?

services[services.length] = this.fakeGato**Histroy**Service;

**Comment by EIBHomeControl** [comment]
looks like.

Update:
it's working now. @simont77 Thanks for ur support.
