### ISSUE TITLE
History Storage and Access

### ISSUE THREAD

**Issue by lespatots** [simont77/fakegato-history#61]
Whilst the Eve app is one of the best Homekit apps around, I was wondering whether it is possible to access the history data for Eve devices from outside the app? If the app can pull the data from  say its weather device could some other interface do it so that it became available in say Node-Red?

**Comment by simont77** [comment]
The history is sent using custom characteristics accessible through Homekit, so, as long as your app complies with the protocol, it should be possible. Details on the decoded protocol is on fakegato wiki. Note however that real Eve accessory may require additional steps for proper communication with the App, so far we have only decoded what needed to emulate history toward Eve.app, and not the other way round.

**Comment by lespatots** [comment]
Thanks for the quick reply. My programming skills aren't up to the the task but perhaps someone else can? Another related question is has anyone looked at Fibaro devices to capture Energy Use as that would be another awsome fix to a proprietary app problem?

**Comment by simont77** [comment]
I don’t know Fibaro devices. It’s a completely different beast
