### ISSUE TITLE
QUESTION: on set EveResetTotal

### ISSUE THREAD

**Issue by mrose17** [simont77/fakegato-history#70]
in addition to doing:

        history.getCharacteristic(CommunityTypes.EveResetTotal).updateValue(value)

should a call be made to `history.cleanPersist()` or something else to tell fakegato to clear the history?

thanks!

**Comment by simont77** [comment]
To remove the history you have to delete the persisted file, if any, but then you have to go in Eve.app and manually remove all the entries, there is no way to do that from the  CleanPersist is an internal function not exposed by fakegato, was added during development but honestly I did not ever use that, I don’t know if it working properly.
the ResetTotal only reset totalizers.

**Comment by mrose17** [comment]
ok, so just checking: what does the plugin have to do besides

    history.getCharacteristic(CommunityTypes.EveResetTotal).updateValue(value)

on a set?

**Comment by simont77** [comment]
When you hit the Reset button on Eve.app, it will send out on the ResetTotal characteristic the time of the reset, so that other Eve.app on other iDevices know the time of the reset. You simple have to catch the update, and reset your local totalizer on your plugin.

**Comment by mrose17** [comment]
Got it, thanks!
