### ISSUE TITLE
Multiple accessories with separate logging

### ISSUE THREAD

**Issue by iRonin** [simont77/fakegato-history#72]
I've been using `homebridge-foobot` plugin [which has logging set up like this](https://github.com/iRonin/homebridge-foobot/blob/7134e143aa8beb364a4a9f679921fc417d3d693a/index.js#L165). 
I've got 3 devices and I can see they all share the same measurements history - only single device writes it and all of them show the same measurements history in Eve.

Should there be different path specified to prevent this @simont77 ?

Thanks!

**Comment by simont77** [comment]
You should use different name and serial number for each accessory to avoid this issue.

**Comment by iRonin** [comment]
That was it, thank you!
