### ISSUE TITLE
googleDrive failed callback

### ISSUE THREAD

**Issue by MaurizioB84** [simont77/fakegato-history#74]
when I lunch the script quickstartGoogleDrive.js and retrieve the link when I put the code into command line I receive the following error:

fs.js:128
  throw new ERR_INVALID_CALLBACK();
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:128:9)
    at Object.writeFile (fs.js:1163:14)
    at storeToken (/homebridge/node_modules/fakegato-history/lib/googleDrive.js:356:6)
    at /homebridge/node_modules/fakegato-history/lib/googleDrive.js:337:7
    at /homebridge/node_modules/fakegato-history/node_modules/google-auth-library/lib/auth/oauth2client.js:154:5
    at Request._callback (/homebridge/node_modules/fakegato-history/node_modules/google-auth-library/lib/transporters.js:106:7)
    at Request.self.callback (/homebridge/node_modules/fakegato-history/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/homebridge/node_modules/fakegato-history/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)

**Comment by NorthernMan54** [comment]
I applied a patch a few minutes ago, it looks like the NodeJS FS Api has changed since this was written.

Please try again

**Comment by MaurizioB84** [comment]
Hello, 

I tried but same error:

Enter the code from that page here: xxxxxxxxxxxxxxx
fs.js:128
  throw new ERR_INVALID_CALLBACK();
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:128:9)
    at Object.writeFile (fs.js:1163:14)
    at storeToken (/homebridge/node_modules/fakegato-history/lib/googleDrive.js:356:6)
    at /homebridge/node_modules/fakegato-history/lib/googleDrive.js:337:7
    at /homebridge/node_modules/fakegato-history/node_modules/google-auth-library/lib/auth/oauth2client.js:154:5
    at Request._callback (/homebridge/node_modules/fakegato-history/node_modules/google-auth-library/lib/transporters.js:106:7)
    at Request.self.callback (/homebridge/node_modules/fakegato-history/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/homebridge/node_modules/fakegato-history/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)

**Comment by NorthernMan54** [comment]
@simont77 Could you publish the latest package on NPM, the fix is good but I think the user is not getting the latest version.

**Comment by MaurizioB84** [comment]
> @simont77 Could you publish the latest package on NPM, the fix is good but I think the user is not getting the latest version.

I download the package from npm, maybe is out of sync?

**Comment by NorthernMan54** [comment]
Yes it would be, as I can only update GitHub

**Comment by simont77** [comment]
Sorry, I’m away from my PC for the next three weeks. I will publish it when I will come back

**Comment by MaurizioB84** [comment]
I can download and install direct from git? Can you please suggest the right command? I'm on docker on raspberry

**Comment by NorthernMan54** [comment]
Try 

```
npm install https://github.com/simont77/fakegato-history
```

**Comment by MaurizioB84** [comment]
ok now works. thanks! can you please help me in order to configure in the right way?

from my understanding I need to add into file fakegato-history.js the following rows:
var FakeGatoHistoryService = require('fakegato-history')(homebridge);
Accessory.log = this.log;
this.loggingService = new FakeGatoHistoryService(accessoryType, Accessory, {
	size:length, 				// optional - if you still need to specify the length
	storage:'googleDrive',
	folder:'fakegatoFolder', 		// folder on Google drive to persist data, 'fakegato' if empty
	keyPath:'/place/to/store/my/keys/' 	// where to find client_secret.json, if empty it will be used the -U homebridge option if present or .homebridge
});

is it right? or where I need to add or which command it's needed to be exec?

many thanks for your help

**Comment by NorthernMan54** [comment]
How is this for a working sample?

https://github.com/NorthernMan54/homebridge-dht/blob/master/index.js

**Comment by MaurizioB84** [comment]
but i need to create a specific js?

**Comment by simont77** [comment]
published as 0.5.4

**Comment by simont77** [comment]
@NorthernMan54 my installation reports a vulnerability in googleapis that is fixed in version s>39.1.0. We are using version 18.0.0. Could you check if we can update the dependency? Thanks

**Comment by NorthernMan54** [comment]
Okay, give me about 48 hours, out of town right now

**Comment by NorthernMan54** [comment]
@simont77 Needed a couple of minor updates to support the change to latest version, but this is resolved.

**Comment by simont77** [comment]
Thanks. Published as v0.5.5
