### ISSUE TITLE
History Graphs are not shown since Eve app update

### ISSUE THREAD

**Issue by sschuste** [simont77/fakegato-history#76]
My Eve app has been updated to v3.8.1 and no longer displays history graphs. Is this a problem to be solved by the EVE developers or by you?

**Comment by DJay-X** [comment]
@simont77 Same problem here after updating to Eve App v3.8.1
Any help is much appreciated. 👍

**Comment by kotashiratsuka** [comment]
same problem

**Comment by ebaauw** [comment]
A far as I can tell, the history protocol itself hasn’t changed, but the Eve app is way more restrictive on what the accessory should look like, before it shows history:
- Sensor with only temperature no longer shows history, but combined temperature, humidity, pressure sensor still works;
- Thermostat without schedule no longer shows history, but thermostat with schedule still works.  Seems like the history for valve position is no longer shown at all;
- Custom service with _Total Consumption_ no longer shows history, but _Outlet_ does.
- Motion and Door sensors still work.

To answer your question: neither, by the plugin developers.

**Comment by simont77** [comment]
I’m away from my PC and with limited internet connection, so I cannot do any test. The update to Eve is a minor release and no firmware update are indicated in the change log, so I would suggest you to try to delete the history from Eve, and, if it doesn’t work, to completely reinstall Eve.

**Comment by simont77** [comment]
Seems ebaauw has already investigated much more...

**Comment by simont77** [comment]
Maybe Eve is more strict on the “fingerprint” as discovered by @stefdude? @ebaauw, what about your combined temperature and plug accessory? Right now fakegato weather probably REQUIRES pressure and humidity, and power REQUIRES outlet

**Comment by ebaauw** [comment]
Oddly, the temperature / on/off hack still works.  My current hypothesis is that the Eve app wants to see the correct service and characteristic(s) for each data type in the history fingerprint.  I plan to do some more rigorous testing this weekend.

**Comment by Samfox2** [comment]
Combined sensor with temp/humidity/air quality also still working...

**Comment by sieren** [comment]
I took a quick look at this yesterday (incl. the repos that are using `fakegato` that are still working).
Everything points towards Eve being more restrictive. However, since all of this is publicly accessible, nothing would stop someone from re-implementing this in a separate app.

It's a shame though Eve is so restrictive about this :/ After all it's just the maker community that's using this and it wouldn't necessarily dig into their overall sales.

**Comment by simont77** [comment]
@ebaauw if you are right it should be possible to fix custom services with consumption only by changing the signature and data portion in fakegato to advertise and send only consumption (should be 0702 section of the current signature). For Energy I did not have a full dump, and it was really an hack over the Room protocol, so it may well be not properly formatted as @stefdude discovered.

**Comment by simont77** [comment]
If that works, it should be possible to add a Temp-only fakegato type advertising and sending only temperature (0102 signature). Any help is appreciated as I’m away from PC for one more week, but I can accept PR. I will make a new branch  fix-signature for that.

**Comment by Samfox2** [comment]
Would temp+humidity-only also be possible?

**Comment by dpecile** [comment]
You can use EVE for IOS 10, until someone can find a fix.
(and disable automatic application updates).

**Comment by ebaauw** [comment]
> If that works, it should be possible to add a Temp-only fakegato type advertising and sending only temperature (0102 signature).

No, that doesn't work.

I did find a hack to expose only temperature history, using the regular `weather` history, see #75.

> Would temp+humidity-only also be possible?

Yes, using the same hack.

**Comment by simont77** [comment]
Did you make some test also for the consumption-only service?

**Comment by ebaauw** [comment]
> Did you make some test also for the consumption-only service?

No, not yet.

**Comment by stef** [comment]
@simont77 when you write @stef then you uselessly invoke me, not the person you wanted to tag.

**Comment by simont77** [comment]
@ebaauw, I made some test.
For power consumption the signature scheme suggested by @stefdude decoding works:

- accessoryType116 = "01 0702";
- accessoryType117 = "01";
- data reduced to 12 bytes, skipping all the 0x00 fields now sent by fakegato.

In this way only power is sent and expected. However Eve still needs the Outlet service to show the history. The good news is that Outlet service can be added to the accessory together with a custom Consumption service (i.e. it is not necessary to add Custom Eve characteristics to  standard Outlet service), so for pure PowerMeter accessory the Outlet could be hidden in Eve, and the powermeter accessory remains visible.

**Comment by simont77** [comment]
Summarizing, some adjustment are required in the plugins using fakegato:

- Weather type needs to conform to one of the options outlined by ebaauw, see https://github.com/simont77/fakegato-history/issues/75
- Power type needs to expose also an Outlet service
- Motion and Door types should still work
- Thermostat type needs to expose the Schedule characteristics

**Comment by Samfox2** [comment]
Sorry,  I am really struggling with the adjustments for a combined temp/humi sensor.
This is what I did before but I like to remove the air pressure:

```javascript
    Service.FakeGatoHistoryService = require('fakegato-history')(homebridge);
    inherits(Service.FakeGatoHistoryService, Service);
    Service.FakeGatoHistoryService.UUID = 'E863F007-079E-48FF-8F27-9C2605A29F52';`
```

```javascript
... 
loggingService = new Service.FakeGatoHistoryService(accessory.context.logType, accessory, { storage: 'fs', path: this.localCache, disableTimer: false });
...
```


```javascript
... 
case "weather:"
                this.log.debug("Temp: %s Press: %s Humi: %s",
                    accessory.context.cacheCurrentTemperature,
                    accessory.context.cacheCurrentAirPressure,
                    accessory.context.cacheCurrentRelativeHumidity);
                accessory.context.loggingService.addEntry({
                    time: moment().unix(),
                    temp: parseFloat(accessory.context.cacheCurrentTemperature),
                    pressure: parseFloat(accessory.context.cacheCurrentAirPressure),
                    humidity: parseFloat(accessory.context.cacheCurrentRelativeHumidity)
                });
                break;
...
```

Where do I have to change the signature?
Would it be possible to provide an example snipplet?

**Comment by simont77** [comment]
I’m copying from ebaauw message:

> So the recipe for a temperature sensor is:
> 
> Expose a Weather service with only a Current Temperature characteristic;
> Expose a regular Temperature Sensor service;
> Expose a regular weather History service (with fingerprint 03 0102 0202 0302).

> And for a temperature/humidity sensor:
> 
> Expose a Weather service with only a Current Temperature characteristic;
> Expose a regular Temperature Sensor service;
> Expose a regular Humidity Sensor service;
> Expose a regular weather History service (with fingerprint 03 0102 0202 0302).

You don’t need to change any signature

**Comment by simont77** [comment]
You could also try to expose a Weather service with Current Temperature AND Humidity Characteristics (i.e. no pressure), and a regular Weather History service.

**Comment by ebaauw** [comment]
That’ll show as unsupported in Apple’s Home app.

**Comment by Samfox2** [comment]
Maybe creating a hidden pressure service is also working.

**Comment by sieren** [comment]
Did anyone dare to talk to Eve support just yet?
I started prototyping an app based on @simont77 s Wiki documentation. It should be fairly doable to get most of the history tracking back into a separate app on the app store if they decide to crack down on fakegato.

![IMG_5650](https://user-images.githubusercontent.com/5174440/64900001-8bc2a480-d68e-11e9-93c1-8c246cf6e1d3.PNG)
(Obv really just a first experiment, no proper graphing, database storage etc. - wonder if anyone else would join me on this cause doing all of this work by myself is quite complex and time intensive)

**Comment by DoTTi72** [comment]
With App version 3.8.3, the history graph is back!

**Comment by ebaauw** [comment]
Indeed.  Eve once again shows history for an accessory and  single _Temperature Sensor_ service, as well as an accessory with _Temperature Sensor_ and Humidity Sensor_ service.  The hack with the _Weather_ service seems no longer needed.

**Comment by sschuste** [comment]
Okay, I guess we all had our fun and the party's over now, right? However, this is a good moment to thank everyone for your effort and most of all @simont77 for his nice piece of software 👍
