### ISSUE TITLE
eve chart axes

### ISSUE THREAD

**Issue by mihailescu2m** [simont77/fakegato-history#82]
this is not an issue with fakegato, ... but:
is there a way to force eve to set y-axis min/max?
e.g. for indoor temperature i would like to have the axis starting from 0 instead of something around the min values.
i thought about setting the first values in the json manually to 0, but they would probably get overwritten in the future.... any ideas?

**Comment by simont77** [comment]
I don’t think it’s possible. You should ask to Eve’s developer.
