### ISSUE TITLE
Eve History week/month view, missing current day

### ISSUE THREAD

**Issue by markus-fischbacher** [simont77/fakegato-history#83]
Hi there, I‘ve noticed that on histories week and month views the line for the current day is not drawn. Could that be a topic of fakegato or more an Eve app issue?

![82514570-765F-4D97-ABAD-904DE61D6E6B](https://user-images.githubusercontent.com/10846308/71644580-0f9aae00-2ccb-11ea-9ffc-b261be5abfb3.png)
![3A4DE31E-09B6-41F3-818E-0D012D1AE286](https://user-images.githubusercontent.com/10846308/71644581-0f9aae00-2ccb-11ea-8292-cafa68199e04.png)

Measure values are available for the whole time. I guess it‘s an app issue. Any ideas?

**Comment by simont77** [comment]
It’s the same also for a genuine Eve Room accessory. It’s related to Eve.app, not to the history

**Comment by markus-fischbacher** [comment]
Thank you for the clarification
