### ISSUE TITLE
Sensor name settable?

### ISSUE THREAD

**Issue by bachandi** [simont77/fakegato-history#88]
Are the sensor names of Temperature, Humidity, ... and their units somwhow settable? I am somehow misusing them for plotting RAM usage but didn't manage to change the humidity title to something else.

**Comment by simont77** [comment]
I'm not sure, but since they are official Homekit Characteristics I don't think that they can be changed. You could only change the name of a Service

**Comment by bachandi** [comment]
But the history would still have Humidity as title on the graph right? So I suppose this is not possible until apple adds the option to have custom graphs. Thanks for the quick reply.

**Comment by simont77** [comment]
I suppose so. Also, the graph is entirely dependent on Eve
