### ISSUE TITLE
wiki suggest [not an issue]

### ISSUE THREAD

**Issue by bwp91** [simont77/fakegato-history#94]
just a suggestion :) 

perhaps a section in the wiki for "homebridge plugins using this library" for developers to be able to see your package in action and look at existing code to help them implement it in their own package.

This would have been a good resource for me!

Ben

**Comment by NorthernMan54** [comment]
This is publicly available via the NPM page for all package's managed by NPM under the "Dependants" tab.  A total of 107 packages leverage fakegato history.

https://www.npmjs.com/package/fakegato-history

**Comment by bwp91** [comment]
Sure as i said it was just a suggestion :)
